// ===== CHRONOS ELITE - PRODUCT DATA =====
const PRODUCTS = [
  {
    id: 1,
    brand: 'Audemars Piguet',
    name: 'Royal Oak Chronograph',
    model: 'Ref. 26331ST',
    price: 48500,
    oldPrice: null,
    category: 'sport',
    gender: 'men',
    material: 'Steel',
    movement: 'Automatic',
    diameter: '41mm',
    waterResistance: '50m',
    image: 'watch_1.png',
    rating: 5,
    reviews: 128,
    badges: ['exclusive'],
    description: 'The Royal Oak Chronograph embodies the ultimate in sporty elegance. Its octagonal bezel with exposed screws and integrated bracelet are icons of horological design. The intricate self-winding movement delivers precision timekeeping with a stunning openworked dial.',
    specs: {
      'Case Material': 'Stainless Steel',
      'Case Diameter': '41mm',
      'Water Resistance': '50 metres',
      'Movement': 'Calibre 2385, Self-winding',
      'Power Reserve': '40 hours',
      'Crystal': 'Sapphire',
      'Bracelet': 'Integrated Steel',
    },
    inStock: true,
    featured: true,
  },
  {
    id: 2,
    brand: 'Patek Philippe',
    name: 'Nautilus Skeleton',
    model: 'Ref. 5726A',
    price: 135000,
    oldPrice: null,
    category: 'dress',
    gender: 'men',
    material: 'Rose Gold',
    movement: 'Automatic',
    diameter: '40.5mm',
    waterResistance: '120m',
    image: 'watch_3.png',
    rating: 5,
    reviews: 84,
    badges: ['limited', 'exclusive'],
    description: 'The pinnacle of haute horlogerie, this Nautilus with skeleton movement exposes the breathtaking mechanical artistry within. Crafted in rose gold with hand-beveled and polished movement components, every detail speaks of unmatched craftsmanship.',
    specs: {
      'Case Material': '18k Rose Gold',
      'Case Diameter': '40.5mm',
      'Water Resistance': '120 metres',
      'Movement': 'Calibre 324 S QA LU 24H/303',
      'Power Reserve': '45 hours',
      'Crystal': 'Sapphire crystal',
      'Bracelet': 'Rose Gold Integrated',
    },
    inStock: true,
    featured: true,
  },
  {
    id: 3,
    brand: 'Rolex',
    name: 'Submariner Date',
    model: 'Ref. 126610LN',
    price: 14500,
    oldPrice: 16000,
    category: 'sport',
    gender: 'men',
    material: 'Steel',
    movement: 'Automatic',
    diameter: '41mm',
    waterResistance: '300m',
    image: 'watch_2.png',
    rating: 5,
    reviews: 412,
    badges: ['sale'],
    description: 'The Submariner is the reference in diving watches. Robust and functional, it was designed to be entirely waterproof. The 2021 version features the new Calibre 3235 movement with a power reserve of approximately 70 hours and improved time-setting mechanisms.',
    specs: {
      'Case Material': 'Oystersteel',
      'Case Diameter': '41mm',
      'Water Resistance': '300 metres',
      'Movement': 'Calibre 3235, Self-winding',
      'Power Reserve': '~70 hours',
      'Crystal': 'Sapphire, Cyclops lens',
      'Bracelet': 'Oyster, Glidelock clasp',
    },
    inStock: true,
    featured: true,
  },
  {
    id: 4,
    brand: 'Hublot',
    name: 'Big Bang Unico',
    model: 'Ref. 411.JB.4901.RT',
    price: 26400,
    oldPrice: null,
    category: 'sport',
    gender: 'men',
    material: 'Black Ceramic',
    movement: 'Automatic',
    diameter: '44mm',
    waterResistance: '100m',
    image: 'watch_4.png',
    rating: 4,
    reviews: 196,
    badges: ['new'],
    description: 'The Big Bang Unico represents the fusion of bold design and in-house chronograph movement. Its black MAGIC ceramic case with carbon fiber dial creates an unmistakably modern aesthetic, while the flyback chronograph function offers maximum performance.',
    specs: {
      'Case Material': 'Micro-blasted black ceramic',
      'Case Diameter': '44mm',
      'Water Resistance': '100 metres',
      'Movement': 'HUB1242 UNICO, Self-winding',
      'Power Reserve': '72 hours',
      'Crystal': 'Anti-scratch sapphire',
      'Bracelet': 'Black rubber & textile',
    },
    inStock: true,
    featured: false,
  },
  {
    id: 5,
    brand: 'IWC Schaffhausen',
    name: 'Portugieser Tourbillon',
    model: 'Ref. IW546302',
    price: 89000,
    oldPrice: null,
    category: 'dress',
    gender: 'men',
    material: 'Platinum',
    movement: 'Manual',
    diameter: '42.3mm',
    waterResistance: '30m',
    image: 'watch_5.png',
    rating: 5,
    reviews: 67,
    badges: ['limited', 'exclusive'],
    description: 'The Portugieser Tourbillon is a masterpiece of precision and craftsmanship. The hand-finished flying tourbillon movement, visible through the exhibition caseback, represents centuries of watchmaking tradition elevated to an art form.',
    specs: {
      'Case Material': 'Platinum 950',
      'Case Diameter': '42.3mm',
      'Water Resistance': '30 metres',
      'Movement': 'Calibre 98950, Manual-winding',
      'Power Reserve': '60 hours',
      'Crystal': 'Sapphire, domed',
      'Bracelet': 'Alligator leather strap',
    },
    inStock: true,
    featured: true,
  },
  {
    id: 6,
    brand: 'Vacheron Constantin',
    name: 'Overseas Perpetual',
    model: 'Ref. 4300V/120R',
    price: 62000,
    oldPrice: null,
    category: 'sport',
    gender: 'unisex',
    material: 'Rose Gold',
    movement: 'Automatic',
    diameter: '41.5mm',
    waterResistance: '150m',
    image: 'watch_1.png',
    rating: 5,
    reviews: 89,
    badges: ['new', 'exclusive'],
    description: 'The Overseas Perpetual Calendar Ultra-Thin combines sporting elegance with one of watchmaking\'s most complex complications. The perpetual calendar mechanism automatically accounts for months of different lengths and leap years until the year 2100.',
    specs: {
      'Case Material': '18k Rose Gold',
      'Case Diameter': '41.5mm',
      'Water Resistance': '150 metres',
      'Movement': 'Calibre 1120 QP/1, Automatic',
      'Power Reserve': '40 hours',
      'Crystal': 'Sapphire crystal',
      'Bracelet': 'Integrated rose gold bracelet',
    },
    inStock: true,
    featured: false,
  },
  {
    id: 7,
    brand: 'A. Lange & Söhne',
    name: 'Lange 1 Tourbillon',
    model: 'Ref. 722.032',
    price: 175000,
    oldPrice: null,
    category: 'dress',
    gender: 'men',
    material: 'White Gold',
    movement: 'Manual',
    diameter: '41.9mm',
    waterResistance: '30m',
    image: 'watch_5.png',
    rating: 5,
    reviews: 43,
    badges: ['limited', 'exclusive'],
    description: 'The LANGE 1 TOURBILLON perpetuates the finest watchmaking traditions of the Glashütte manufacture. The hand-engraved three-quarter plate in German silver and the outsize date mechanism are hallmarks of A. Lange & Söhne excellence.',
    specs: {
      'Case Material': '18k White Gold',
      'Case Diameter': '41.9mm',
      'Water Resistance': '30 metres',
      'Movement': 'Calibre L961.2, Manual-winding',
      'Power Reserve': '72 hours',
      'Crystal': 'Sapphire crystal, anti-reflective',
      'Bracelet': 'Crocodile leather',
    },
    inStock: false,
    featured: false,
  },
  {
    id: 8,
    brand: 'Cartier',
    name: 'Santos de Cartier',
    model: 'Ref. WSSA0029',
    price: 9800,
    oldPrice: 11200,
    category: 'dress',
    gender: 'unisex',
    material: 'Steel',
    movement: 'Automatic',
    diameter: '39.8mm',
    waterResistance: '100m',
    image: 'watch_2.png',
    rating: 4,
    reviews: 287,
    badges: ['sale'],
    description: 'Born from a passion for aviation, the Santos de Cartier is one of the world\'s first wristwatches. The iconic square case with visible screws and integrated bracelet remain as relevant today as when Alberto Santos-Dumont wore it on his historic flights.',
    specs: {
      'Case Material': 'Stainless Steel',
      'Case Diameter': '39.8mm',
      'Water Resistance': '100 metres',
      'Movement': 'Calibre 1847 MC, Automatic',
      'Power Reserve': '42 hours',
      'Crystal': 'Sapphire crystal',
      'Bracelet': 'Dual material interchangeable',
    },
    inStock: true,
    featured: false,
  },
  {
    id: 9,
    brand: 'Omega',
    name: 'Seamaster Professional',
    model: 'Ref. 210.30.42.20.03.001',
    price: 6700,
    oldPrice: null,
    category: 'sport',
    gender: 'men',
    material: 'Steel',
    movement: 'Automatic',
    diameter: '42mm',
    waterResistance: '300m',
    image: 'watch_2.png',
    rating: 5,
    reviews: 534,
    badges: ['new'],
    description: 'The Seamaster Professional 300M is the watch of choice for professionals and diving enthusiasts alike. The new generation features Master Chronometer certification and the innovative ceramic dial with applied hour markers.',
    specs: {
      'Case Material': 'Stainless Steel',
      'Case Diameter': '42mm',
      'Water Resistance': '300 metres',
      'Movement': 'Calibre 8800, Co-Axial',
      'Power Reserve': '55 hours',
      'Crystal': 'Domed scratch-resistant sapphire',
      'Bracelet': 'Stainless steel mesh',
    },
    inStock: true,
    featured: false,
  },
  {
    id: 10,
    brand: 'Jaeger-LeCoultre',
    name: 'Reverso Classic',
    model: 'Ref. Q3858522',
    price: 11500,
    oldPrice: null,
    category: 'dress',
    gender: 'women',
    material: 'Steel',
    movement: 'Manual',
    diameter: '23.1×38.2mm',
    waterResistance: '30m',
    image: 'watch_3.png',
    rating: 5,
    reviews: 156,
    badges: ['exclusive'],
    description: 'The Reverso remains one of the most iconic watch designs in history. Created in 1931 for polo players, its reversible case allows the case back to protect the dial during play. The skeletonized version transforms it into a miniature work of art.',
    specs: {
      'Case Material': 'Stainless Steel',
      'Case Diameter': '23.1×38.2mm',
      'Water Resistance': '30 metres',
      'Movement': 'Calibre 822/2, Manual-winding',
      'Power Reserve': '42 hours',
      'Crystal': 'Sapphire crystal',
      'Bracelet': 'Alligator leather',
    },
    inStock: true,
    featured: false,
  },
  {
    id: 11,
    brand: 'Richard Mille',
    name: 'RM 011 Felipe Massa',
    model: 'Ref. RM011-03',
    price: 215000,
    oldPrice: null,
    category: 'sport',
    gender: 'men',
    material: 'Titanium',
    movement: 'Automatic',
    diameter: '50×40mm',
    waterResistance: '50m',
    image: 'watch_4.png',
    rating: 5,
    reviews: 31,
    badges: ['limited', 'exclusive'],
    description: 'The RM 011 represents the pinnacle of high-tech watchmaking. The multilayered sandwich movement visible through the tonneau-shaped case showcases the most advanced materials in watchmaking — grade 5 titanium, PTFE, and carbon nanotubes.',
    specs: {
      'Case Material': 'Grade 5 Titanium',
      'Case Diameter': '50×40mm',
      'Water Resistance': '50 metres',
      'Movement': 'Calibre RMAC2, Skeletonized',
      'Power Reserve': '55 hours',
      'Crystal': 'Sapphire, curved',
      'Bracelet': 'Natural rubber strap',
    },
    inStock: true,
    featured: false,
  },
  {
    id: 12,
    brand: 'Breguet',
    name: 'Tradition Minute',
    model: 'Ref. 7097BB/G1/9WU',
    price: 44000,
    oldPrice: 48000,
    category: 'dress',
    gender: 'men',
    material: 'White Gold',
    movement: 'Manual',
    diameter: '41mm',
    waterResistance: '30m',
    image: 'watch_1.png',
    rating: 4,
    reviews: 72,
    badges: ['sale'],
    description: 'The Tradition collection was created to celebrate the traditional craftsmanship of Abraham-Louis Breguet. The movement is displayed on the front of the dial, giving an unprecedented view of the mechanical ballet within.',
    specs: {
      'Case Material': '18k White Gold',
      'Case Diameter': '41mm',
      'Water Resistance': '30 metres',
      'Movement': 'Calibre 567, Manual-winding',
      'Power Reserve': '50 hours',
      'Crystal': 'Sapphire crystal',
      'Bracelet': 'Alligator leather with pin buckle',
    },
    inStock: true,
    featured: false,
  },
];

const CATEGORIES = [
  {
    id: 'sport',
    name: 'Sport',
    label: 'Collection',
    image: 'watch_2.png',
    count: 6,
    desc: 'Professional Sport',
  },
  {
    id: 'dress',
    name: 'Dress',
    label: 'Collection',
    image: 'watch_3.png',
    count: 5,
    desc: 'Grand Complications',
  },
  {
    id: 'limited',
    name: 'Limited Editions',
    label: 'Exclusive',
    image: 'watch_1.png',
    count: 4,
    desc: 'Rare & Exclusive',
  },
];

const BRANDS = ['Rolex', 'Patek Philippe', 'Audemars Piguet', 'A. Lange & Söhne', 'Vacheron Constantin', 'Jaeger-LeCoultre', 'IWC Schaffhausen', 'Breguet', 'Cartier', 'Omega', 'Hublot', 'Richard Mille'];

const TESTIMONIALS = [
  {
    text: 'The Patek Philippe I purchased from Chronos Elite exceeded all expectations. The authentication certificate and the white-glove delivery service made the experience truly unforgettable.',
    name: 'Alexander K.',
    role: 'Private Collector',
    initials: 'AK',
  },
  {
    text: 'I\'ve purchased from many prestigious watch retailers, but Chronos Elite stands apart. Their expertise and the condition of the timepieces is absolutely flawless.',
    name: 'Victoria L.',
    role: 'Watch Enthusiast',
    initials: 'VL',
  },
  {
    text: 'Exceptional service from selection to delivery. The Richard Mille I acquired was accompanied by comprehensive documentation and is in pristine condition. Highly recommended.',
    name: 'Michael S.',
    role: 'Business Executive',
    initials: 'MS',
  },
];
